### ISSUE TITLE
Crash when plan id is wrong

### ISSUE THREAD

**Issue by hkroger** [monostream/helmi#32]
If I try to create bindings and plan_id is wrong, helmi is throwing nasty error like this:

```
019/03/07 10:35:15 http: panic serving 172.16.0.6:55772: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc0002ad680)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x108d1a0, 0x1cd4b30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/monostream/helmi/pkg/catalog.(*Service).ReleaseSection(0xc0002ad7c0, 0x0, 0xc000253c00, 0x10, 0x10, 0xc0003b5a00, 0xe, 0xc0003b6aab, 0xc, 0x100, ...)
	/go/src/github.com/monostream/helmi/pkg/catalog/catalog.go:761 +0x6be
github.com/monostream/helmi/pkg/release.GetCredentials(0xc0002bfd00, 0xc0002aa7b0, 0x24, 0xc0002aa7e0, 0x24, 0xc0000486da, 0xb, 0x10927c0, 0xc0003d4b60, 0x10927c0)
	/go/src/github.com/monostream/helmi/pkg/release/release.go:312 +0x14cc
github.com/monostream/helmi/pkg/broker.(*Broker).Bind(0xc000275bf0, 0x1323de0, 0xc0003becf0, 0xc0000486da, 0xb, 0xc0000486f7, 0x13, 0x0, 0x0, 0xc0002aa7e0, ...)
	/go/src/github.com/monostream/helmi/pkg/broker/broker.go:266 +0xe3
github.com/monostream/helmi/vendor/github.com/pivotal-cf/brokerapi.serviceBrokerHandler.bind(0x132d100, 0xc000275bf0, 0x132dc40, 0xc00027a8a0, 0x1323120, 0xc0002041c0, 0xc000208800)
	/go/src/github.com/monostream/helmi/vendor/github.com/pivotal-cf/brokerapi/api.go:397 +0x4ad
github.com/monostream/helmi/vendor/github.com/pivotal-cf/brokerapi.serviceBrokerHandler.bind-fm(0x1323120, 0xc0002041c0, 0xc000208800)
	/go/src/github.com/monostream/helmi/vendor/github.com/pivotal-cf/brokerapi/api.go:78 +0x69
...
```

I believe this might be due to plan object being empty if plan_id is wrong. This is easy to fix but what should be right way:
a) Fix the potential crash by add `if plan != nil { /* Do here the thing that might crash otherwise */ }` 
b) Validate and throw error early if plan_Id is invalid?

**Comment by hkroger** [comment]
Actually same happens when create is being provisioned and plan id is wrong..
